/*
 Seed initial data without deleting existing rows.
 - Creates 4 users (admin, vendor, 2 clients) if missing
 - Backfills review ownership (user_id) where missing
 - Optionally creates a demo review with findings for the vendor (idempotent)

 Safe to re-run multiple times. Uses findOrCreate and skips updates.
*/

const path = require('path');

// Load environment (mirror server.js behavior)
const dotenv = require('dotenv');
if (process.env.NODE_ENV === 'production') {
  dotenv.config({ path: path.resolve(process.cwd(), '.env.production') });
} else {
  dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });
}

const sequelize = require('../config/Database');

// Load models and associations
const User = require('../models/user');
// New requirements: make reviews owned by a user (no table drops)
const Review = require('../models/review');
const ReviewFinding = require('../models/review_finding');

async function main() {
  const t0 = Date.now();
  console.log('\n[seed] Starting seed...');

  try {
    await sequelize.authenticate();
    console.log('[seed] DB connection OK');
  } catch (e) {
    console.error('[seed] DB connection failed:', e.message);
    process.exit(1);
  }

  // 1) Ensure core users
  const HASH = '$2a$10$5CGgCv.sxWjtvdKCIWtKI.Ek4ry8T608hGIVYwD95/QH3pKdnUaga';
  const usersData = [
    { first_name: 'admin', name: 'admin', email: 'admin@gmail.com', password: HASH, role: 'admin' },
    { first_name: 'Ioan', name: 'Timis', email: 'timisionut2000@gmail.com', password: HASH, role: 'vendor' },
    { first_name: 'User2', name: 'User2', email: 'user2@example.com', password: HASH, role: 'client' },
    { first_name: 'User3', name: 'User3', email: 'user3@example.com', password: HASH, role: 'client' },
  ];

  const usersByEmail = {};
  for (const u of usersData) {
    const [user] = await User.findOrCreate({
      where: { email: u.email },
      defaults: { ...u, createdAt: new Date(), updatedAt: new Date() },
    });
    usersByEmail[u.email] = user;
  }
  console.log('[seed] Users ensured:', Object.keys(usersByEmail));

  const vendor = usersByEmail['timisionut2000@gmail.com'] || usersByEmail['admin@gmail.com'];
  if (!vendor) {
    throw new Error('No vendor/admin user available for resource ownership.');
  }

  // 1.b) Backfill review ownership (no deletes). Assign vendor as owner where missing.
  try {
    const [affected] = await Review.update(
      { user_id: vendor.id },
      { where: { user_id: null } }
    );
    if (affected) console.log(`[seed] Backfilled user_id for ${affected} review(s).`);
  } catch (e) {
    console.warn('[seed] Skipped review backfill (table may be missing or column absent):', e.message);
  }

  // (resources seeding removed as requested)

  // 4) Optional: ensure a minimal demo review with findings for the vendor (idempotent)
  try {
    const existingDemo = await Review.findOne({ where: { user_id: vendor.id, scope: 'seed:demo' } });
    if (!existingDemo) {
      const demo = await Review.create({
        user_id: vendor.id,
        scope: 'seed:demo',
        guidelines: 'Demo review generated by seed',
        meta: { seed: true }
      });
      await ReviewFinding.bulkCreate([
        {
          review_id: demo.id,
          file: 'client/src/app/page.jsx',
          lineStart: 1,
          lineEnd: 1,
          severity: 'info',
          title: 'Demo tip',
          description: 'Acesta este un exemplu de finding generat de seed.',
          guideline: 'General',
          recommendation: 'Nicio acțiune necesară.',
          effortHours: 0.1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          review_id: demo.id,
          file: 'server/controllers/Auth.js',
          lineStart: 1,
          lineEnd: 2,
          severity: 'warn',
          title: 'Demo warning',
          description: 'Exemplu pentru UI: severitate warn.',
          guideline: 'Style',
          recommendation: 'Revizuiește mesajele de log.',
          effortHours: 0.2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log('[seed] Created demo review with 2 findings for vendor');
    } else {
      console.log('[seed] Demo review already present for vendor');
    }
  } catch (e) {
    console.warn('[seed] Skipped demo review seeding (tables/columns may be missing):', e.message);
  }

  const dt = ((Date.now() - t0) / 1000).toFixed(2);
  console.log(`[seed] Done in ${dt}s`);
  await sequelize.close();
  process.exit(0);
}

main().catch(async (err) => {
  console.error('[seed] Failed:', err);
  try { await sequelize.close(); } catch (_) {}
  process.exit(1);
});
